name: Docker

on:
  workflow_dispatch: {}
  # schedule:
  #   - cron: "0 16 * * 1"
  push:
    branches:
      - main
    paths:
      - Dockerfile
      - requirements.txt
  pull_request:
    paths:
      - Dockerfile
      - requirements.txt

concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  docker:
    name: docker build
    uses: Docker-Collection/reusable-workflows/.github/workflows/docker-build.yml@main
    with:
      docker_name: "ghcr.io/docker-collection/oci-cli"
      docker_label_author: "Efina"
      docker_label_title: "Docker OCI-CLI"
      docker_label_description: "Oracle CLI on Docker"
      version_detecter: true
      version_detecter_file: "requirements.txt"
      version_detecter_var: "oci-cli=="
      version_detecter_cut: "3"
